name: Build map

on:
  push:
    paths:
      - "data/**"
      - "build_map.R"
      - ".github/workflows/build-map.yml"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up R (latest stable)   # <-- clave
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.1'             # o 'latest'
          use-public-rspm: true          # binarios rápidos de CRAN

      - name: Set up Pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Ver R y sesión (debug opcional)
        run: |
          Rscript -e 'cat(R.version.string, "\n")'
          Rscript -e 'sessionInfo()'

      - name: Instalar paquetes
        run: |
          Rscript -e 'install.packages(c("readr","dplyr","leaflet","htmlwidgets","commonmark"))'

      - name: Construir mapa
        run: |
          Rscript build_map.R

      - name: Commit salida (index.html + glosas)
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: rebuild site"
          file_pattern: |
            index.html
            glosas/**
            glosas_md/**
