name: Build & Deploy Map

on:
  push:
    paths:
      - "data/**/*.csv"          # <-- AJUSTA si tu CSV está en otra carpeta
      - "build_map.R"            # <-- AJUSTA si tu script se llama distinto
      - "scripts/**/*.R"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'

      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::readr
            any::dplyr
            any::leaflet
            any::htmlwidgets
            any::stringi
            any::fs
            any::commonmark
            any::htmltools
            any::purrr

      - name: Build map (Rscript)
        run: Rscript build_map.R    # <-- AJUSTA si tu script tiene otro nombre

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs               # <-- Debe contener index.html

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
